name: release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build release zip
        run: |
          zip -r TradeShieldTBC.zip CHANGELOG.md Core.lua TradeShieldTBC.toc

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: TradeShieldTBC.zip

